// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiGIn.Data;

namespace SiGIn.Data.Migrations
{
    [DbContext(typeof(SiGInContext))]
    [Migration("20190615014713_add_tipo_descuento")]
    partial class add_tipo_descuento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SiGIn.Models.Entities.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("Nombre");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Actividad");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.Almacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CantidadEntrada");

                    b.Property<int?>("CantidadSalida");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<DateTime?>("FechaEntrada");

                    b.Property<DateTime?>("FechaSalida");

                    b.Property<int?>("IdProducto");

                    b.Property<int?>("IdTalla");

                    b.Property<int?>("Total");

                    b.HasKey("Id");

                    b.ToTable("Almacen");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.Auxiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CantPedidos");

                    b.Property<int?>("CantProceso");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<DateTime?>("Fecha");

                    b.Property<int?>("PorCortar");

                    b.Property<string>("Producto");

                    b.Property<string>("Talla");

                    b.HasKey("Id");

                    b.ToTable("Auxiliar");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.AuxiliarFemenino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<int?>("F3525");

                    b.Property<int?>("F363");

                    b.Property<int?>("F384");

                    b.Property<int?>("F405");

                    b.Property<int?>("F426");

                    b.Property<int?>("F447");

                    b.Property<string>("Totales");

                    b.HasKey("Id");

                    b.ToTable("AuxiliarFemenino");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgenciaBancariaCuc");

                    b.Property<string>("AgenciaBancariaCup");

                    b.Property<string>("CodigoNit");

                    b.Property<string>("CodigoReeup");

                    b.Property<string>("CuentaBancariaCuc");

                    b.Property<string>("CuentaBancariaCup");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("DictadaPor");

                    b.Property<string>("DomicilioLegal");

                    b.Property<DateTime?>("FechaResolucion");

                    b.Property<string>("Nacionalidad");

                    b.Property<string>("Nombre");

                    b.Property<string>("Representante");

                    b.Property<string>("ResolucionNo");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.Nomina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cantidad");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<DateTime?>("Fecha");

                    b.Property<int?>("IdActividad");

                    b.Property<string>("IdPedido");

                    b.Property<int?>("IdProducto");

                    b.Property<int?>("IdTalla");

                    b.Property<int?>("IdTrabajador");

                    b.HasKey("Id");

                    b.ToTable("Nomina");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.PedProdTalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CantEnteros");

                    b.Property<int?>("Cantidad");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<int?>("IdProducto");

                    b.Property<int?>("IdTalla");

                    b.Property<string>("NoPedido");

                    b.Property<int?>("PorVender");

                    b.Property<int?>("Vendidos");

                    b.HasKey("Id");

                    b.ToTable("PedProdTalla");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Abierto");

                    b.Property<int?>("CantidadPedido");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<DateTime?>("FechaPedido");

                    b.Property<int?>("IdEmpresa");

                    b.Property<int?>("IdProducto");

                    b.Property<string>("NoPedido");

                    b.Property<int?>("PorVender");

                    b.Property<int?>("Vendidos");

                    b.HasKey("Id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Observaciones");

                    b.Property<decimal>("PrecioUnitarioCuc");

                    b.Property<decimal>("PrecioUnitarioCup");

                    b.Property<string>("Um");

                    b.HasKey("Id");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.Talla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Talla");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.TipoDescuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TipoDescuento");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActividadDesempeña");

                    b.Property<string>("Apellidos");

                    b.Property<bool>("Contratado");

                    b.Property<string>("ContratadoPor");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<DateTime?>("FehaExpedicionTcp");

                    b.Property<string>("Ni");

                    b.Property<int?>("NoRegistroCreador");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Trabajador");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.TrabajadorDescuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<DateTime?>("Fecha");

                    b.Property<int?>("Monto");

                    b.Property<int?>("TipoDescuentoId");

                    b.Property<int?>("TrabajadorId");

                    b.HasKey("Id");

                    b.HasIndex("TipoDescuentoId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("TrabajadorDescuento");
                });

            modelBuilder.Entity("SiGIn.Models.Entities.TrabajadorDescuento", b =>
                {
                    b.HasOne("SiGIn.Models.Entities.TipoDescuento", "TipoDescuento")
                        .WithMany()
                        .HasForeignKey("TipoDescuentoId");

                    b.HasOne("SiGIn.Models.Entities.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId");
                });
#pragma warning restore 612, 618
        }
    }
}
